name: 'Get and Cache Dependencies'
description: 'get dependencies and cahce them.'
inputs:
  caching:
    description: 'weather to cache dependency or not'
    required: false
    default: 'true'
output:
  used-cache:
  description: 'weather to cache used or not
  value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
         npm ci
         echo "::set-output name=cache::'${{ inputs.caching }}'"
      shell: bash
